import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "../globals.css";
import { Toaster } from "sonner";

const barlow = Barlow({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WarJong",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${barlow.className} bg-surface h-screen`}>
        {children}
        <Toaster richColors position="bottom-right" />
      </body>
    </html>
  );
}
